## 회귀분석 (Regression)


- 독립변수(X)와 종속변수(Y)의 관계식에서
  독립변수가 한 단위 증가할 때 종속변수가 얼마나 영향을 받는지 분석
  

[예] 연속형변수와 연속형 변수를 비교할 때


- 나이(X)가 많을 수록 소득(Y)가 높은지 분석
- 광고지불비(X)에 따라 판매량이 영향을 받는지 분석
- 가계 수입과 사교육비 지출 사이에 관계가 있는지 분석



[참고그림] '모두의 딥러닝' 교재에서

<img src='./imgs/regression1.png' width='500'>
<img src='./imgs/regression2.png' width='500'>
<img src='./imgs/regression3.png' width='500'>

** 회귀분석 종류

1) 단순회귀 분석 : 독립변수가 1개
        
        ` 광고지불비(X)를 이용하여 상품 매출액(Y) 예측할 때
        
2) 다중회귀 분석 : 독립변수가 2개 이상
       
       ` 어린이 연령(X1)과 하루 평균 학습시간(X2)를 이용하여 그 어린이의 성적(Y)을 예측하고자 할 때

---
#### 앞에서는   scipy 의 선형회귀를 이용하고 아래는 sklearn의 머신러닝 종류 중 선형회귀 모델 사용

---

## 회귀분석 예제 - 보스턴 주택가격



#### [ 절차 ]
    (1) 데이타 읽어오기

    (2) 데이터와 레이블 분리 변수 선언

    (3) 훈련데이터와 테스트 데이터로 분리하기

    (4) 모델로 학습하기

    (5) 검증하기

In [1]:

# 보스턴 주택가격 데이터셋
from sklearn.datasets import load_boston

# 회귀분석을 위한 패키기
from sklearn.linear_model import LinearRegression

# 학습용, 검증용 데이터를 나누기 위한 패키기
from sklearn.model_selection import train_test_split

In [4]:
boston = load_boston()
print(boston.DESCR) #데이터 설명

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**

    :Number of Instances: 506

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
        - B        1000(Bk - 0.63)^2 where Bk is the proportion of black people by town
        - LSTAT    % lower status of the population
        - MEDV     Median value of owner-occupied homes in $1000's

    :Missing Attribute Values: None

    :Creator: Harrison, D. and Rubinfeld, D.L.

This is a copy of UCI ML housing dataset.
https://archive.ics.uci.edu/ml/machine-learning-databases/housing/


This dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.

The Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic
prices and the demand for clean air', J. Environ. Economics & Management,
vol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics
...', Wiley, 1980.   N.B. Various transformations are used in the table on
pages 244-261 of the latter.

The Boston house-price data has been used in many machine learning papers that address regression
problems.

.. topic:: References

   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.
   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.

In [5]:
import pandas as pd

df =  pd.DataFrame(boston.data)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [8]:
# 컬럼 이름 넣어주기
df.columns = boston.feature_names
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [14]:
# 데이터 x와 라벨(답) y로 나누기
x = df
# 답
y = boston.target

In [27]:
# 훈련데이터와 테스트로 분리
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=0)

In [28]:
# 모델에 학습
lr = LinearRegression() #선형회귀모델로 학습
lr.fit(x_train, y_train)

LinearRegression()

In [29]:
# 검증하기
print('훈련데이터 점수 :', lr.score(x_train, y_train))
print('테스트데이터 점수 :', lr.score(x_test, y_test))

훈련데이터 점수 : 0.7697699488741149
테스트데이터 점수 : 0.6354638433202129

In [32]:
import numpy as np
sample_x = np.array([[0.00632, 18.0, 2.31, 0.0, 0.538, 6.575, 65.2, 4.0900, 1.0, 296.0, 15.3, 396.90, 4.98]])
sample_y = lr.predict(sample_x)
sample_y

C:\Users\kosmo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([30.46090593])

속성정보:

    - CRIM     인구 1인당 범죄 수
    - ZN       25000평방 피트 이상의 주거 구역 비중
    - INDUS    소매업 외 상업이 차지하는 면접 비율
    - CHAS     찰스강 위치 변수 (1: 강주변, 0:이외 )
    - NOX      일산화질소 농도 (parts per 10 million)
    - RM       집의 평균 방수
    - AGE      1940년 이전에 지어진 비율
    - DIS      5가지 보스턴 시 고용 시설까지의 거리
    - RAD      순환고속도로의 접근 용이성
    - TAX      $10000 달러당 부동산 세율 총계
    - PTRATIO  지역별 학생과 교사 비율
    - B        지역별 흑인 비율
    - LSTAT    급여가 낮은 직업에 종사하는 인구 비율(%)
    
    
    - MEDV     가격단위($1000)